name: Ruby

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]


jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Check links
        run: |
          gem install awesome_bot
          awesome_bot readme.md --allow-ssl --allow 302,429 --white-list 'https://mywhitelisteddomain.com,https://mysecondwhitelisteddomain.com'
